package view;

import controller.ProdutoController;
import model.Categoria;
import javax.swing.*;
 
import java.util.List;

public class ProdutoView extends JPanel {
  //  private Object cbCategoria;
        private JComboBox<Categoria> cbCategoria = new JComboBox<>();

        //método construtor
    public ProdutoView() {
        controller = new ProdutoController();      
        initComponents();
        preencherComboCategorias(controller.obterCategorias());
    }

    // Referência para o Controller
    private final ProdutoController controller;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPreco = new javax.swing.JFormattedTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadastro de Produtos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 6, -1, -1));

        jLabel2.setText("Nome:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));
        add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 40, 286, -1));

        jLabel3.setText("Descrição:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, -1, -1));
        add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 80, 286, -1));

        jLabel4.setText("Preço:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, -1, -1));

        jLabel5.setText("Categoria:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 163, -1, -1));

        jComboBox.setName("cbCategoria"); // NOI18N
        jComboBox.addActionListener(this::jComboBoxActionPerformed);
        add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 160, 186, -1));

        jButton3.setText("Cancelar");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 219, -1, -1));

        jButton1.setText("Limpar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 219, -1, -1));

        jButton2.setText("Salvar");
        jButton2.addActionListener(this::btnSalvar);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 219, -1, -1));

        try {
            txtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar
        // Evento do botão Salvar
        acaoSalvar();
        };
    
    public void preencherComboCategorias(List<Categoria> categorias) {
        System.out.println("Categorias carregadas: " + categorias.size());  
                
         // 1. Criamos o modelo usando a classe Categoria explicitamente
        DefaultComboBoxModel<model.Categoria> model = new DefaultComboBoxModel<>();
    
        // 2. Adicionamos os objetos reais
        for (model.Categoria cat : categorias) {
            model.addElement(cat);
        }
    
    // 3. Vinculamos ao componente
    // IMPORTANTE: Se você renomeou o combo para cbCategoria, use esse nome aqui.
    // Se ainda for jComboBox, use jComboBox.
    jComboBox.setModel(model); 
    
    // 4. Forçar atualização visual
    jComboBox.revalidate();
    jComboBox.repaint();                   
    }//fim prencher combo categorias
    
    
    private void acaoSalvar() {
            try {
                String nome = txtNome.getText();
                String descricao = txtDescricao.getText();
                double preco = Double.parseDouble(txtPreco.getText());
                 
                 // Recuperamos o OBJETO Categoria inteiro que está selecionado
                Categoria selecionada = (Categoria) cbCategoria.getSelectedItem();
                
                // Enviamos para o Controller processar                       
               if (selecionada != null) {
            // A LINHA QUE FALTAVA:
            controller.salvarProduto(nome, preco, descricao, selecionada);
            
            JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!");
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria!");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Erro: Preço inválido. Use ponto para decimais.");
    }
}

        private void limparCampos() {
            txtNome.setText("");
            txtPreco.setText("");
            txtDescricao.setText("");
            cbCategoria.setSelectedIndex(0);
            txtNome.requestFocus();
    }//GEN-LAST:event_btnSalvar

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<model.Categoria> jComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPreco;
    // End of variables declaration//GEN-END:variables

   
}
